### ISSUE TITLE
Feature Request: Option to open in a hover preview window

### ISSUE THREAD

**Issue by j-adel** [PKM-er/Obsidian-Surfing#149]
### Feature Requested

So I've been using this plugin a lot for very useful feature: whenever I forget the definition of a word, I would run the Wikipedia search command to see its page. It'd be a lot more smooth if the web page were to pop up in a hover preview window, like note links in Obsidian Page preview.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
If you would like to use hover editor plugin with this feature, it will be easy to have a hover preview window opened; If not, it will be diffcult to handle when you want to trigger a hover preview window.

**Comment by XMB-7** [comment]
> it will be easy to have a hover preview window opened

It is easy, but not handy. A new tab is always open when clicking on a link, so we have to execute a command provided by Hover Editor to convert it to a popover. And it would be awesome if the default behavior could be changed and there is an option allowing a link to be opened directly in a popover.

**Comment by j-maffe** [comment]
Yes, exactly. My thought was actually a simpler and more direct implementation like the current Hover Editor. You just hover over the link while holding ctrl and the popover shows up. I don't even think the Hover Editor plugin would be needed, just the Preview core plugin. This feature along with [Obsidian Wiki Search](https://github.com/StrangeGirlMurph/obsidian-wikipedia-search) would be a match made in heaven :D
