### ISSUE TITLE
[Bug]: 打开surfing标签后，拖拽文件无法形成置入链接

### ISSUE THREAD

**Issue by zhl111** [PKM-er/Obsidian-Surfing#161]
### Bug Description

关闭surfing标签后，拖文件入ob就可以生成链接，打开则不行

### Obsidian Version

1.1.9

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
不理解。你可以提供更多的上下文信息吗？什么链接，怎么打开，以及是 Surfing 标签打开的情况下，这个文件可以打开吗？

**Comment by Quorafind** [comment]
已修复。
