### ISSUE TITLE
[Bug]: 对PDF导出功能似乎有干扰：无序列表前面的序号不见了。

### ISSUE THREAD

**Issue by zhaoscsc** [PKM-er/Obsidian-Surfing#163]
### Bug Description

当开启surfing插件的时候，导出的PDF不能正常显示无序列表。
当关闭surfing插件的时候，就恢复正常了。

### Obsidian Version

0.8.13

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
已修复。
