### ISSUE TITLE
[Bug]: 默认搜索引擎无论选哪个都是google搜索

### ISSUE THREAD

**Issue by HopeLHP** [PKM-er/Obsidian-Surfing#190]
### Bug Description

默认搜索引擎无论选哪个都是google搜索，只有选择自定义才能按照自定义的搜索引擎搜索。

### Obsidian Version

1.3.5

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
已经修复。
