### ISSUE TITLE
[Bug]: Link does not work in Properties

### ISSUE THREAD

**Issue by kmaustral** [PKM-er/Obsidian-Surfing#196]
### Bug Description

When clicking a link in Properties (Obsidian version 1.4.2), it sends the URL to an external browser. 

### To Reproduce

1. Put link in Properties
2. Click link

### Obsidian Version

1.4.2

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
fixed.
