### ISSUE TITLE
Feature Request: Add a command as `Open with Hover Editor` in the context menu.

### ISSUE THREAD

**Issue by XMB-7** [PKM-er/Obsidian-Surfing#210]
### Feature Requested

It would be handy to display a popover in the editing mode.

### Relevant Screenshot

![image](https://github.com/PKM-er/Obsidian-Surfing/assets/65625632/564dfd09-47b8-42f7-a9f6-53555b8d4064)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Supported via context menu, won't support via ctrl key.

**Comment by XMB-7** [comment]
It would be awesome to also have a corresponding command in the command palate so that users could assign a hotkey for it to easily call out a popover, when cursor locates inside a link.

**Comment by Quorafind** [comment]
Won't support either. Actually, I never use hover editor for surfing. Wait anyone else who want to contribute.
