### ISSUE TITLE
Feature Request: 建议可以自定义某些跳转协议不弹出预览框

### ISSUE THREAD

**Issue by likemuuxi** [PKM-er/Obsidian-Surfing#219]
### Feature Requested

自定义某些跳转协议不弹出预览框，或者只有网页相关协议可以弹出
### Relevant Screenshot

![image](https://github.com/PKM-er/Obsidian-Surfing/assets/85612715/4b7a29df-4c6c-4cf3-8996-b6c85e17cc0e)

### Checklist

- [x] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
已经修复

**Comment by likemuuxi** [comment]
> 已经修复
经测试还是弹出预览框
![image](https://github.com/PKM-er/Obsidian-Surfing/assets/85612715/e2c3ccf4-c0c8-4297-8a42-faafd3c427c0)
![image](https://github.com/PKM-er/Obsidian-Surfing/assets/85612715/531e3125-6451-4acd-919a-c3c9023f366f)

**Comment by Quorafind** [comment]
https://github.com/PKM-er/Obsidian-Surfing/releases/tag/0.9.4 再更新一次就行，忘了处理预览模式下的情况。
