### ISSUE TITLE
[Bug]: Cant drag and drop into canvas

### ISSUE THREAD

**Issue by DaitiDay** [PKM-er/Obsidian-Surfing#224]
### Bug Description

After opening a page in the plugin, drag and dropping links, text, pictures or anything into a canvas or note do not copy the text. Hovering the canvas/note with mouse button pressed shows the "plus" icon, but after releasing the mouse button nothing happens.
Copy-Paste works as expected.

### To Reproduce

1. Enable the Surfing plugin
2. Open a web page
3. Highlight something, drag and drop it into a canvas/note
4. Nothing happens

### Obsidian Version

1.5.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by calmwaves111** [comment]
+1，This bug is very serious and affects me a lot

**Comment by Quorafind** [comment]
Got fixed already.

**Comment by calmwaves111** [comment]
There still seems to be in trouble
If I open a web page, drag and drop still doesn't work
If I close all web pages, drag and drop is available
