### ISSUE TITLE
[Bug]: Text not visible in Obsidian

### ISSUE THREAD

**Issue by alx-xlx** [PKM-er/Obsidian-Surfing#235]
### Bug Description

The text is not visible I have to select it then it is visible

### Relevant Screenshot

![6sAfEy30jf](https://github.com/PKM-er/Obsidian-Surfing/assets/42188371/9b4d67cb-3cc0-46f5-8125-d3c0bebc278f)

### To Reproduce

1. open obsidian
2. open [link](https://raw.githubusercontent.com/civictech-India/constitution-of-india/main/constitution_of_india.json)

### Obsidian Version

1.5.12

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Please try again with default theme:

![Clip_2024-04-22_21-50-05](https://github.com/PKM-er/Obsidian-Surfing/assets/13215013/20b5536b-c42f-4feb-934d-f02ba68d145e)
