### ISSUE TITLE
[Bug]: Enabling inline preview makes callouts/code blocks fail to render as expected in live preview

### ISSUE THREAD

**Issue by Krakor92** [PKM-er/Obsidian-Surfing#239]
### Bug Description

When enabling the new inline preview feature, callouts and computed code blocks (dataview, js-engine, ...) are not rendered correctly in live preview, as if they were in source mode.

### To Reproduce

1. Open the sandbox vault
2. Install the Surfing plugin (v0.9.9)
3. Tick the `Enable inline preview`
4. Launch `Reload app without saving` command

### Obsidian Version

1.5.12

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed already.
