### ISSUE TITLE
[Bug]: 启动内联预览会导致文档多出一份文档属性源码

### ISSUE THREAD

**Issue by lv-ago** [PKM-er/Obsidian-Surfing#241]
### Bug Description

在启动了内联预览后就会出现这样的情况
![2D6EB0DC088C9007D5CE50881E51FFA7](https://github.com/PKM-er/Obsidian-Surfing/assets/50603713/99ffa6c3-80bd-41b0-be4e-14a327ee34ac)

### To Reproduce

https://github.com/PKM-er/Obsidian-Surfing/assets/50603713/6417f252-794c-4e83-9399-dd43d87c4b42

### Obsidian Version

v1.5.12

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by 05019527** [comment]
关掉内联预览就正常了

**Comment by Quorafind** [comment]
已修复
