### ISSUE TITLE
Feature Request: Hope to disable "/" quick search

### ISSUE THREAD

**Issue by buynonsense** [PKM-er/Obsidian-Surfing#254]
### Feature Requested

When I use "/" the cursor jumps to the url bar, but I'm just writing a comment.Even when I tried disabling this feature on the relevant website, it still didn't work. I hope to be able to update the global disable this quick search feature.
当我使用"/"键时光标跳转到了url栏，而我只是在写注释。即使当我在尝试禁用相关网站上的这个功能时依然没有效果。我希望能够更新全局禁用这个快速搜索的功能。

### Relevant Screenshot

![image](https://github.com/PKM-er/Obsidian-Surfing/assets/97596221/9a27946a-e8d7-482c-90d9-81a84e4fa3a8)
![image](https://github.com/PKM-er/Obsidian-Surfing/assets/97596221/0cb68266-e976-42b9-ab79-beb4c9c988ce)

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Support disable this feature in 0.9.13
