### ISSUE TITLE
[Bug]: 打开通义千问页面，整个网页变灰。

### ISSUE THREAD

**Issue by Wooden-Gear** [PKM-er/Obsidian-Surfing#257]
### Bug Description

打开通义千问的页面，点击登陆，出现登录框，之后点击登录框的任何地方，整个页面都会变灰。

### Relevant Screenshot

点击登陆框，就会变成图2，典籍登录框之外，则没关系。
图1
![Quicker_20240616_015327](https://github.com/PKM-er/Obsidian-Surfing/assets/143693404/e5927b6b-442e-40dc-937f-f9084eaef531)
页面变灰
图2
![Quicker_20240616_015400](https://github.com/PKM-er/Obsidian-Surfing/assets/143693404/60c2b7b8-df2f-4a50-9c4c-8dda3c9b855f)

### To Reproduce

通义千问页面，点击登陆，出现登录框，点击登录框，出现bug。

### Obsidian Version

0.9.12

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
通义千问的限制

**Comment by Wooden-Gear** [comment]
> 通义千问的限制

啊！这都限制啊！
