### ISSUE TITLE
[Bug]: Disable / to search when on these sites doesn't work

### ISSUE THREAD

**Issue by ianTevesAcc** [PKM-er/Obsidian-Surfing#258]
### Bug Description

Im trying to prevent surfing from searching when on the following sites but unfortunately it's not working. I have placed these in the `Disable / to search when on these sites` setting.

notion,craft,http//localhost:8888/lab,localhost,lab

### Relevant Screenshot

![image](https://github.com/PKM-er/Obsidian-Surfing/assets/105651670/8605d36d-d15f-492e-8a32-58e6c08bfbbb)
![image](https://github.com/PKM-er/Obsidian-Surfing/assets/105651670/ab8f2f60-086f-4323-ac0e-7952e4c60cbf)

### To Reproduce

1. install and activate surfing plugin
2. place a website link (eg. https://google.com) inside the `Disable / to search when on these sites` setting
3. open the website in surfing
4. press /

Expected:
To be able to type / inside any input element inside the surfing plugin page. (e. search '/' inside the google textarea input element)

Result:
cursor moves to surfing plugin Search Query area instead of allowing to type / inside the google search input element.

### Obsidian Version

latest version

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Fixed in 0.9.13
