### ISSUE TITLE
[Bug]: Notion使用“/”命令会跳到地址栏

### ISSUE THREAD

**Issue by ic1123** [PKM-er/Obsidian-Surfing#259]
### Bug Description

Obsidian版本号V1.6.3，Surfing插件的版本为0.9.12

通过Surfing插件登录Notion，打算联动使用，结果发现在输入“/”命令符号时，会跳到Obsidian上方的地址栏中，导致原有位置的操作失效。

使用了“搜索选项——当在这些网站中禁止按/来搜索的功能[notion,craft]”，但是这好像不起作用
<img width="1226" alt="微信图片_20240617155852" src="https://github.com/PKM-er/Obsidian-Surfing/assets/89264167/1c11dc94-49dc-4ac5-a1e5-3f32be178332">
<img width="707" alt="2" src="https://github.com/PKM-er/Obsidian-Surfing/assets/89264167/48cc78a5-2416-4f94-a060-d5c3d847ab92">

### Obsidian Version

V1.6.3

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
已修复
