### ISSUE TITLE
Feature Request: History or browser cache settings?

### ISSUE THREAD

**Issue by tp1415926535** [PKM-er/Obsidian-Surfing#276]
### Feature Requested

As far as I know, the browser cache takes up about 1G or so, and I'd like to know where the cache folder is for this plugin, or can set its path.
Also hopefully there will be added functionality to delete history, cookies, cache, etc.
I see in the description that there is a `Clear browsing history` command, but after installing the latest version (0.9.12) I can't find it in the command panel of obsidian.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by Quorafind** [comment]
Fixed.
