### ISSUE TITLE
[Bug]: The webpage that is open cannot log in.

### ISSUE THREAD

**Issue by yiweiguo126** [PKM-er/Obsidian-Surfing#277]
### Bug Description

https://tongyi.aliyun.com/
Upon opening the login interface on the website, the entire webpage turns gray after you click on it, and the login interface disappears.
<img width="810" alt="image" src="https://github.com/user-attachments/assets/157bcdc7-b39d-4811-a210-dfa74d5051bc">

![error1](https://github.com/user-attachments/assets/7923077e-6880-460c-8924-37a31e91c87f)

### To Reproduce

1.Go to the website:https://tongyi.aliyun.com/
2.Click to log in
3.When you enter or click in the pop-up window, the page will disappear and turn gray.

### Obsidian Version

1.6.7

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Quorafind** [comment]
Cannot repro
