### ISSUE TITLE
[Bug]: The "i" hotkey to jump to searchbar is unchangeable

### ISSUE THREAD

**Issue by Mack127444** [PKM-er/Obsidian-Surfing#278]
### Bug Description

In many cases, if you are typing in a new tab and you are tying in the quick switcher or the top search bar, clicking the "i" key sends your cursor to the center search bar. While it is a nice feature, it makes you unable to search for anything with an "i" in it when inside the new tab window. Is there a way to change or remove this?

### To Reproduce

Go to new tab
Select the top search bar, or open the MAKE.md quick switcher
Click the "i" key and the cursor disappears to the center search bar for some reason

### Obsidian Version

0.9.12

### web-browser-only

- [X] Did you install only one web browser plugin?

### Checklist

- [X] I updated to the latest version of the plugin.

**Comment by Evantix** [comment]
I just installed the surfing plugin, and when I press the letter "i" in the top search bar, it jumps to the middle search bar. This is annoying, so I had to disable the "Show search bar on empty page" feature.
![image](https://github.com/user-attachments/assets/18bd4155-24b9-420b-a1e4-ca4721a9e906)

**Comment by Quorafind** [comment]
Support disable the function in 0.9.13
