### ISSUE TITLE
Feature Request: Disable the "/" hotkey (which access the address bar) in certain websites 

### ISSUE THREAD

**Issue by Michael679089** [PKM-er/Obsidian-Surfing#283]
### Feature Requested

Every time I am typing, I keep accidentally access the address bar when I pressed the "/" key. 

I would like this option to be disabled when I'm in certain websites for example Google Sheets, or when I'm in Google Docs.

So that I don't have to use my mouse to get back on the line I'm typing on. 

### Relevant Screenshot

https://github.com/user-attachments/assets/6ffdb719-6c94-4d7e-9412-82c68c948206

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by hyperrealist** [comment]
I think there is already an option in the `Search` tab of the settings page called `"Disable / to search when on these sites"`, but it never worked for me. Perhaps this should be tagged as a bug instead of a feature request.

**Comment by Quorafind** [comment]
Supported in 0.9.13
