### ISSUE TITLE
Feature Request: Add an option to disable or remap the current behavior when pressed `/`

### ISSUE THREAD

**Issue by hyperrealist** [PKM-er/Obsidian-Surfing#287]
### Feature Requested

There are far too many websites I would like to have `/` not hijacked for search (any website with text input, including this one). I would also like to use local web services like xtermjs, vscode, etc. that would benefit from disabling this.

Please let the users disable the current `/` behavior or remap it to a shortcut (most browsers on macOS use cmd + L for this feature).

### Relevant Screenshot

https://github.com/user-attachments/assets/53e5405c-e0f0-446a-9b67-8891200a91d5

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by hyperrealist** [comment]
#283 requests to disable this in specific websites, but the option for it that already exists in the search tab of the settings page did not work for me on any website I add there.

**Comment by Quorafind** [comment]
Supported in 0.9.13
